version: "2"

linters:
  default: standard

  enable:
    - bodyclose
    - contextcheck
    - gocritic
    - gosec
    - nilerr
    - revive

formatters:
  enable:
    - gofmt

run:
  modules-download-mode: readonly